FROM realityone/rust-openwrt-1402-uclibc:latest

ENV CC_mips_unknown_linux_uclibc "mips-openwrt-linux-gcc"
ENV PATH "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/OpenWrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin"
ENV STAGING_DIR "/OpenWrt/staging_dir/"
